---
title: "CSR with sf"
subtitle: ""
author: "Lisa Pramann & Caitlin Sarro"
institute: "Hertie School"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts] 
    lib_dir: sf_presentation_files
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
      hash: true
---
class: inverse, center, middle
name: welcome

```{css, echo=FALSE} 
@media print { # print out incremental slides; see https://stackoverflow.com/questions/56373198/get-xaringan-incremental-animations-to-print-to-pdf/56374619#56374619
  .has-continuation {
    display: block !important;
  }
}
```

```{r setup, include=FALSE}
# figures formatting setup
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  prompt = T,
  fig.align="center", #fig.width=6, fig.height=4.5, 
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T, #echo=F, warning=F, message=F
  engine.opts = list(bash = "-l")
  )
## Next hook based on this SO answer: https://stackoverflow.com/a/39025054
knit_hooks$set(
  prompt = function(before, options, envir) {
    options(
      prompt = if (options$engine %in% c('sh','bash')) '$ ' else 'R> ',
      continue = if (options$engine %in% c('sh','bash')) '$ ' else '+ '
      )
})
```

 
```{r}
# Importing the relevant libraries
# install.packages("hrbrthemes")
# install.packages("fontawesome")
library(hrbrthemes)
library(fontawesome)



# install.packages("pagedown")
# install.packages("xaringan")
library(pagedown)
library(xaringan)

```

---


# Intro | What is a “Coordinate Reference System” (CRS) ?

<html><div style='float:left'></div><hr color='#EB811B' size=1px style="width:1000px; margin:auto;"/></html>

---
# Introduction to sf package
## What it does

- Bullet 1 test test
- Bullet 2
- Bullet 3

---
## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

## Print the Slides

```{r}

```


